field: 2202461d-285c-4b02-9aa1-66fea5228786 # Site Custom Navigation
fieldLayouts:
  b4ba9cdc-c76f-4947-96bd-d1d849d10e7b:
    tabs:
      -
        elements:
          -
            fieldUid: 8ca9ce47-bfd4-4d95-bdae-4074e4ad3960 # Entry Link
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 52259224-3ac1-4577-b963-4783958d3fad # Child List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8ca9ce47-bfd4-4d95-bdae-4074e4ad3960: # Entry Link
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: entryLink
    instructions: ''
    name: 'Entry Link'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  52259224-3ac1-4577-b963-4783958d3fad: # Child List
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: childList
    instructions: ''
    name: 'Child List'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - d1a91586-3ffb-4320-b6da-dd4e58f7d449 # Child Link
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_2_childlist}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: entryField
name: 'Entry Field'
sortOrder: 1
