field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  47b1e4e9-907c-49cf-a4cd-e4cbf7080830:
    tabs:
      -
        elements:
          -
            fieldUid: 7a43c953-3dd4-40d5-bbe8-498e7411a32c # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a864cf15-74b2-4267-9853-a82a0c804294 # Sub Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7d2c0254-7894-48c8-abcf-dd3ec03f49c4 # Projects Links Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b36f866-3a9d-4f45-8cb6-6088f01e8769 # Projects Links Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3e896876-b4ce-4985-96b2-98cc8df171d6 # Projects Links Project
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1305912f-e7bd-4297-b074-b9c45da795db # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1b36f866-3a9d-4f45-8cb6-6088f01e8769: # Projects Links Heading
    columnSuffix: camfacai
    contentColumnType: text
    fieldGroup: null
    handle: projectsLinksHeading
    instructions: ''
    name: 'Projects Links Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3e896876-b4ce-4985-96b2-98cc8df171d6: # Projects Links Project
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: projectsLinksProject
    instructions: ''
    name: 'Projects Links Project'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 60bdcc03-a906-4791-b6e7-8c566657eb2e
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 735ca862-9f3f-4c35-bf19-de9077fcd63f
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_3_projectslinksproject}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  7a43c953-3dd4-40d5-bbe8-498e7411a32c: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  7d2c0254-7894-48c8-abcf-dd3ec03f49c4: # Projects Links Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: projectsLinksIcon
    instructions: ''
    name: 'Projects Links Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8dec0694-79e6-43cf-9898-1f9633496ab5' # Videos
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:5258e7de-fdc7-487f-9a45-2e567a7b1251' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  1305912f-e7bd-4297-b074-b9c45da795db: # Module ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  a864cf15-74b2-4267-9853-a82a0c804294: # Sub Heading
    columnSuffix: uuewtcyo
    contentColumnType: text
    fieldGroup: null
    handle: subHeading
    instructions: ''
    name: 'Sub Heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: homeIntro
name: 'Home Intro'
sortOrder: 1
