field: 48b393c6-8937-4f82-9402-a1d6bd982171 # Page Content
fieldLayouts:
  f865ff31-7ceb-4bc1-ae65-f6679e24780b:
    tabs:
      -
        elements:
          -
            fieldUid: ad097efc-8a00-4502-aa2d-99d0770e4be9 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c37466f8-6142-4c68-92e1-70efb1e5670e # Image Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1a6f251f-db8b-417e-9f70-337a037f8eed # Module ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1a6f251f-db8b-417e-9f70-337a037f8eed: # Module ID
    columnSuffix: ufirzojn
    contentColumnType: text
    fieldGroup: null
    handle: moduleId
    instructions: ''
    name: 'Module ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  ad097efc-8a00-4502-aa2d-99d0770e4be9: # Heading
    columnSuffix: ckvifsfx
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c37466f8-6142-4c68-92e1-70efb1e5670e: # Image Url
    columnSuffix: atbukokt
    contentColumnType: string(255)
    fieldGroup: null
    handle: imageUrl
    instructions: 'Put Image Url'
    name: 'Image Url'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
handle: iframeModule
name: 'iFrame Module'
sortOrder: 4
