fieldLayouts:
  b83eb617-b962-4945-b2a8-302e06d680e3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 40816dba-f57f-46d5-92bb-b0be3bd8ffc0 # External URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fb84bf1a-5324-4c6b-998c-a9fc6d5d1134 # Hide from Navigation?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d5c3224c-f766-4625-ac73-882d233e1ff0 # Is External URL?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e7cdd12-5e29-4b9e-9527-e21c05429c77 # Is Page Link Disabled?
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Settings'
        sortOrder: 2
handle: default
hasTitleField: true
name: Default
section: df154360-edf0-4e44-bac6-0cdfa4e2b52d # Project Categories
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
