columnSuffix: jjrgjavy
contentColumnType: text
fieldGroup: 069db710-b502-4f33-949f-2f58b1543b35 # Common - Project Data
handle: headerText
instructions: 'Add custom header text instead of title.'
name: 'Header Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
