columnSuffix: zatcnyew
contentColumnType: text
fieldGroup: 2456b677-3768-4a36-9c40-49c6498d1a4d # Common - Page Data
handle: hgTitle
instructions: 'Add custom header title (instead of entry name).'
name: 'Header Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
