columnSuffix: null
contentColumnType: string
fieldGroup: 2c26ccab-40f5-4820-a185-63ccdc2d7585 # Globals - Site Footer
handle: listLink
instructions: ''
name: 'List Link'
searchable: false
settings:
  contentTable: '{{%stc_listlink}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
