columnSuffix: jfufujji
contentColumnType: text
fieldGroup: 2c26ccab-40f5-4820-a185-63ccdc2d7585 # Globals - Site Footer
handle: mailingAddress
instructions: ''
name: 'Mailing Address'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
