columnSuffix: lseovngy
contentColumnType: string(7)
fieldGroup: 2456b677-3768-4a36-9c40-49c6498d1a4d # Common - Page Data
handle: pageAccentBgColor
instructions: 'Set accent bg color (for buttons specifically).'
name: 'Accent Bg Color'
searchable: false
settings:
  defaultColor: '#ededed'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
