defaultPlacement: end
enableVersioning: false
handle: bjorvikaArticles
name: 'Bjørvika Articles'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  27aff492-2400-42d9-878a-bd134e93ebd6: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page\bjorvika-articles
    uriFormat: 'bjorvika/{slug}'
structure:
  maxLevels: 1
  uid: fac5c9bb-f92c-4800-8f3b-0f70678f592f
type: structure
