defaultPlacement: end
enableVersioning: false
handle: projectCategories
name: 'Project Categories'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  27aff492-2400-42d9-878a-bd134e93ebd6: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page\project-categories
    uriFormat: 'prosjekter/{slug}'
structure:
  maxLevels: 1
  uid: 946db914-0ca2-4196-8c7d-61905508c828
type: structure
