defaultPlacement: end
enableVersioning: false
handle: projects
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  27aff492-2400-42d9-878a-bd134e93ebd6: # $DEFAULT_SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: page\projects
    uriFormat: 'prosjekter/{slug}'
structure:
  maxLevels: 1
  uid: 287401bf-1671-4a02-bdca-2d036e56df70
type: structure
